#!/usr/bin/env python3
"""Compile French medical aliases and drug mappings for Smart Search.

Includes:
- French brand names / Specialites courantes -> DCI / molecules actives (BDPM / ANSM)
- Medical abbreviations and acronyms (EDN / R2C / Colleges medicaux)
- Clinical synonyms and semiological equivalences
"""

from __future__ import annotations

import argparse
import gzip
import json
from pathlib import Path
import re
import unicodedata

SPACE = re.compile(r"\s+")

def normalize(value: str) -> str:
    value = unicodedata.normalize("NFKC", value or "").casefold()
    value = value.replace("’", "'").replace("–", "-").replace("—", "-")
    return SPACE.sub(" ", value).strip()

FRENCH_DRUGS_MAPPING = {
    # Antalgiques / Antipyretiques / AINS / Corticoides
    "doliprane": "paracetamol",
    "dafalgan": "paracetamol",
    "efferalgan": "paracetamol",
    "perfalgan": "paracetamol",
    "spasfon": "phloroglucinol",
    "kardegic": "acide acetylsalicylique",
    "aspegic": "acide acetylsalicylique",
    "aspirine": "acide acetylsalicylique",
    "advil": "ibuprofene",
    "nurofen": "ibuprofene",
    "antarene": "ibuprofene",
    "spidifen": "ibuprofene",
    "apranax": "naproxene",
    "bi-profenid": "ketoprofene",
    "profenid": "ketoprofene",
    "toprec": "ketoprofene",
    "voltarene": "diclofenac",
    "flector": "diclofenac",
    "celebrex": "celecoxib",
    "ixprim": "tramadol / paracetamol",
    "zaldiar": "tramadol / paracetamol",
    "topalgic": "tramadol",
    "contramal": "tramadol",
    "lamaline": "paracetamol / cafeine / opium",
    "izalgi": "paracetamol / opium",
    "skenan": "morphine",
    "actiskenan": "morphine",
    "sevredol": "morphine",
    "moscontin": "morphine",
    "oxynorm": "oxycodone",
    "oxycontin": "oxycodone",
    "durogesic": "fentanyl",
    "abstral": "fentanyl",
    "instanyl": "fentanyl",
    "cortancyl": "prednisone",
    "solupred": "prednisolone",
    "solumedrol": "methylprednisolone",
    "celestene": "betamethasone",
    "diprostene": "betamethasone",
    "hydrocortisone": "hydrocortisone",

    # Antibiotiques / Anti-infectieux / Antifongiques
    "clamoxyl": "amoxicilline",
    "augmentin": "amoxicilline / acide clavulanique",
    "oroben": "amoxicilline",
    "bristopen": "oxacilline",
    "orbene": "cloxacilline",
    "tazocilline": "piperacilline / tazobactam",
    "ticarpen": "ticarcilline",
    "rocephine": "ceftriaxone",
    "claforan": "cefotaxime",
    "fortum": "ceftazidime",
    "orelox": "cefpodoxime",
    "oroken": "cefixime",
    "zinnat": "cefuroxime",
    "kefandol": "cefamandole",
    "tavanic": "levofloxacine",
    "ciflox": "ciprofloxacine",
    "oflocet": "ofloxacine",
    "izilox": "moxifloxacine",
    "pyostacine": "pristinamycine",
    "josacine": "josamycine",
    "rovamycine": "spiramycine",
    "zithromax": "azithromycine",
    "zeclar": "clarithromycine",
    "rulid": "roxithromycine",
    "vibramycine": "doxycycline",
    "doxydo": "doxycycline",
    "tolycycline": "doxycycline",
    "bactrim": "sulfamethoxazole / trimethoprime",
    "flagyl": "metronidazole",
    "targocid": "teicoplanine",
    "vancocine": "vancomycine",
    "amukin": "amikacine",
    "gentalline": "gentamicine",
    "nebomycine": "tobramycine",
    "rifadine": "rifampicine",
    "rimifon": "isoniazide",
    "myambutol": "ethambutol",
    "pirilene": "pyrazinamide",
    "fungizone": "amphotericine b",
    "triflucan": "fluconazole",
    "sporanox": "itraconazole",
    "vfend": "voriconazole",
    "cancidas": "caspofungine",
    "lamisil": "terbinafine",
    "zovirax": "aciclovir",
    "zelitrex": "valaciclovir",
    "cymevan": "ganciclovir",
    "valcyte": "valganciclovir",
    "tamiflu": "oseltamivir",
    "vemlidy": "tenofovir alafenamide",
    "viread": "tenofovir disoproxil",
    "epivir": "lamivudine",
    "truvada": "emtricitabine / tenofovir disoproxil",
    "biktarvy": "bictegravir / emtricitabine / tenofovir alafenamide",
    "triumeq": "abacavir / dolutegravir / lamivudine",
    "tivicay": "dolutegravir",

    # Cardiologie / Vasculaire / Antihypertenseurs / Antithrombotiques
    "tahor": "atorvastatine",
    "crestor": "rosuvastatine",
    "elisor": "pravastatine",
    "vytorin": "ezetimibe / simvastatine",
    "ezetrol": "ezetimibe",
    "lipanthyl": "fenofibrate",
    "lasilix": "furosemide",
    "burinex": "bumetanide",
    "fludex": "indapamide",
    "esidrex": "hydrochlorothiazide",
    "aldactone": "spironolactone",
    "inspra": "eplerenone",
    "coversyl": "perindopril",
    "triatec": "ramipril",
    "renitec": "enalapril",
    "zestril": "lisinopril",
    "acuitel": "quinapril",
    "cozaar": "losartan",
    "tareg": "valsartan",
    "aprovel": "irbesartan",
    "micardis": "telmisartan",
    "olmetec": "olmesartan",
    "entresto": "sacubitril / valsartan",
    "sectral": "acebutolol",
    "tenormine": "atenolol",
    "cardensiel": "bisoprolol",
    "detensiel": "bisoprolol",
    "lopressor": "metoprolol",
    "seloken": "metoprolol",
    "avlocardyl": "propranolol",
    "temerit": "nebivolol",
    "kredex": "carvedilol",
    "trandate": "labetalol",
    "amlor": "amlodipine",
    "loxen": "nicardipine",
    "chronadalate": "nifedipine",
    "adalate": "nifedipine",
    "isoptine": "verapamil",
    "tildiem": "diltiazem",
    "cordarone": "amiodarone",
    "rythmol": "propafenone",
    "flecaine": "flecainide",
    "sotalex": "sotalol",
    "digoxine": "digoxine",
    "plavix": "clopidogrel",
    "brilique": "ticagrelor",
    "efient": "prasugrel",
    "eliquis": "apixaban",
    "xarelto": "rivaroxaban",
    "pradaxa": "dabigatran",
    "lixiana": "edoxaban",
    "coumadine": "warfarine",
    "previscan": "fluindione",
    "sintrom": "acenocoumarol",
    "lovenox": "enoxaparine",
    "fraxiparine": "nadroparine",
    "innohep": "tinzaparine",
    "arixtra": "fondaparinux",
    "heparine": "heparine sodique",
    "calciparine": "heparine calcique",
    "natispray": "trinitrine",
    "nitriderm": "trinitrine",
    "corvasal": "molsidomine",
    "ikorel": "nicorandil",
    "ranexa": "ranolazine",
    "procoralan": "ivabradine",

    # Gastro-enterologie / Metabolisme / Diabetologie
    "inexium": "esomeprazole",
    "mopral": "omeprazole",
    "zoltum": "omeprazole",
    "eupantol": "pantoprazole",
    "inipomp": "pantoprazole",
    "ogast": "lansoprazole",
    "pariet": "rabeprazole",
    "tagamet": "cimetidine",
    "azantac": "ranitidine",
    "gaviscon": "alginate de sodium / bicarbonate de sodium",
    "maalox": "hydroxyde d'aluminium / hydroxyde de magnesium",
    "motilium": "domperidone",
    "primperan": "metoclopramide",
    "vogalene": "metopimazine",
    "zophren": "ondansetron",
    "kytril": "granisetron",
    "imodium": "loperamide",
    "tiorfan": "racecadotril",
    "smecta": "diosmectite",
    "duphalac": "lactulose",
    "forlax": "macrogol",
    "movicol": "macrogol",
    "fivasa": "mesalazine",
    "pentasa": "mesalazine",
    "rowasa": "mesalazine",
    "delursan": "acide ursodesoxycholique",
    "ursolvan": "acide ursodesoxycholique",
    "glucophage": "metformine",
    "stagid": "metformine",
    "diamicron": "gliclazide",
    "amarel": "glimepiride",
    "daonil": "glibenclamide",
    "januvia": "sitagliptine",
    "xelevia": "sitagliptine",
    "galvus": "vildagliptine",
    "onglyza": "saxagliptine",
    "trajenta": "linagliptine",
    "victoza": "liraglutide",
    "saxenda": "liraglutide",
    "ozempic": "semaglutide",
    "wegovy": "semaglutide",
    "trulicity": "dulaglutide",
    "forxiga": "dapagliflozine",
    "jardiance": "empagliflozine",
    "invokana": "canagliflozine",
    "lantus": "insuline glargine",
    "toujeo": "insuline glargine",
    "levemir": "insuline detemir",
    "tresiba": "insuline degludec",
    "novorapid": "insuline aspart",
    "humalog": "insuline lispro",
    "apidra": "insuline glulisine",
    "actrapid": "insuline humaine rapide",
    "umuline": "insuline humaine",
    "glucagen": "glucagon",

    # Neurologie / Psychiatrie / Sommeil
    "levothyrox": "levothyroxine",
    "l-thyroxin": "levothyroxine",
    "deroxat": "paroxetine",
    "seroplex": "escitalopram",
    "seropram": "citalopram",
    "prozac": "fluoxetine",
    "zoloft": "sertraline",
    "effexor": "venlafaxine",
    "cymbalta": "duloxetine",
    "ixel": "milnacipran",
    "laroxyl": "amitriptyline",
    "anafranil": "clomipramine",
    "norset": "mirtazapine",
    "athymil": "mianserine",
    "valdoxan": "agomelatine",
    "terian": "buspirone",
    "xanax": "alprazolam",
    "lexomil": "bromazepam",
    "temesta": "lorazepam",
    "valium": "diazepam",
    "seresta": "oxazepam",
    "urbanyl": "clobazam",
    "tranxene": "clorazepate",
    "lysanxia": "prazepam",
    "rivotril": "clonazepam",
    "stilnox": "zolpidem",
    "imovane": "zopiclone",
    "atarax": "hydroxyzine",
    "theralene": "alimemazine",
    "risperdal": "risperidone",
    "zyprexa": "olanzapine",
    "abilify": "aripiprazole",
    "solian": "amisulpride",
    "leponex": "clozapine",
    "haldol": "haloperidol",
    "largactil": "chlorpromazine",
    "tiapridal": "tiapride",
    "nozinan": "levomepromazine",
    "loxapac": "loxapine",
    "teralithe": "lithium",
    "depakote": "divalproate de sodium",
    "depakine": "acide valproique / valproate de sodium",
    "tegretol": "carbamazepine",
    "trileptal": "oxcarbazepine",
    "lamictal": "lamotrigine",
    "keppra": "levetiracetam",
    "vimpat": "lacosamide",
    "zonegran": "zonisamide",
    "fycompa": "perampanel",
    "neurontin": "gabapentine",
    "lyrica": "pregabaline",
    "gardenal": "phenobarbital",
    "sinemet": "levodopa / carbidopa",
    "modopar": "levodopa / benserazide",
    "requip": "ropinirole",
    "sifrol": "pramipexole",
    "neupro": "rotigotine",
    "mantadix": "amantadine",
    "azilect": "rasagiline",
    "comtan": "entacapone",
    "ebixa": "memantine",
    "aricept": "donepezil",
    "exelon": "rivastigmine",
    "reminyl": "galantamine",

    # Pneumologie / Allergologie
    "ventoline": "salbutamol",
    "airomir": "salbutamol",
    "bricanyl": "terbutaline",
    "atrovent": "ipratropium",
    "spiriva": "tiotropium",
    "serevent": "salmeterol",
    "foradil": "formoterol",
    "oxis": "formoterol",
    "onbrez": "indacaterol",
    "seretide": "salmeterol / fluticasone",
    "symbicort": "budesonide / formoterol",
    "innovair": "beclometasone / formoterol",
    "relvar": "fluticasone / vilanterol",
    "pulmicort": "budesonide",
    "flixotide": "fluticasone",
    "qvar": "beclometasone",
    "singulair": "montelukast",
    "xolair": "omalizumab",
    "dupixent": "dupilumab",
    "nasonex": "mometasone",
    "zyrtec": "cetirizine",
    "clarityne": "loratadine",
    "aerius": "desloratadine",
    "xyzal": "levocetirizine",
    "kestin": "ebastine",
    "telfast": "fexofenadine",

    # Rhumatologie / Immunologie / Hematologie / Oncologie
    "methotrexate": "methotrexate",
    "novatrex": "methotrexate",
    "metoject": "methotrexate",
    "plaquenil": "hydroxychloroquine",
    "salazopyrine": "sulfasalazine",
    "arava": "leflunomide",
    "imurel": "azathioprine",
    "cellcept": "mycophenolate mofetil",
    "myfortic": "acide mycophenolique",
    "neoral": "ciclosporine",
    "sandimmun": "ciclosporine",
    "prograf": "tacrolimus",
    "advagraf": "tacrolimus",
    "enbrel": "etanercept",
    "humira": "adalimumab",
    "remicade": "infliximab",
    "simponi": "golimumab",
    "cimzia": "certolizumab pegol",
    "roactemra": "tocilizumab",
    "mabthera": "rituximab",
    "rixathon": "rituximab",
    "stelara": "ustekinumab",
    "cosentyx": "secukinumab",
    "taltz": "ixekizumab",
    "tremfya": "guselkumab",
    "rinvoq": "upadacitinib",
    "xeljanz": "tofacitinib",
    "olumiant": "baricitinib",
    "colchicine": "colchicine",
    "colchimax": "colchicine / poudre d'opium",
    "zyloric": "allopurinol",
    "adenuric": "febuxostat",
    "fosamax": "acide alendronique",
    "actonel": "acide risedronique",
    "aclasta": "acide zoledronique",
    "prolia": "denosumab",
    "forsteo": "teriparatide",
    "tardyferon": "sulfate ferreux",
    "fumafer": "fumarate ferreux",
    "ferinject": "carboxymaltose ferrique",
    "venofer": "hydroxyde ferrique saccharose",
    "speciafoldine": "acide folique",
    "vitamine b12": "cyanocobalamine",
    "decadron": "dexamethasone",
}

FRENCH_ACRONYMS_MAPPING = {
    # Cardiovasculaire
    "hta": "hypertension arterielle",
    "idm": "infarctus du myocarde",
    "sca": "syndrome coronarien aigu",
    "scast+": "syndrome coronarien aigu avec sus-decalage st",
    "scast-": "syndrome coronarien aigu sans sus-decalage st",
    "stemi": "infarctus avec sus-decalage st",
    "nstemi": "infarctus sans sus-decalage st",
    "avc": "accident vasculaire cerebral",
    "ait": "accident ischemique transitoire",
    "fa": "fibrillation atriale",
    "acfa": "arythmie complete par fibrillation atriale",
    "fl": "flutter atrial",
    "bav": "bloc auriculo-ventriculaire",
    "bav1": "bloc auriculo-ventriculaire du 1er degre",
    "bav2": "bloc auriculo-ventriculaire du 2eme degre",
    "bav3": "bloc auriculo-ventriculaire complet du 3eme degre",
    "bbd": "bloc de branche droit",
    "bbg": "bloc de branche gauche",
    "hbp": "hypertrophie benigne de la prostate",
    "oap": "oedeme aigu du poumon",
    "ep": "embolie pulmonaire",
    "tvp": "thrombose veineuse profonde",
    "mtev": "maladie thromboembolique veineuse",
    "ic": "insuffisance cardiaque",
    "ic-fevg": "insuffisance cardiaque a fraction d'ejection preservee",
    "ic-fer": "insuffisance cardiaque a fraction d'ejection reduite",
    "fevg": "fraction d'ejection du ventricule gauche",
    "rac": "retrecissement aortique",
    "ia": "insuffisance aortique",
    "im": "insuffisance mitrale",
    "rm": "retrecissement mitral",
    "aomi": "arteriopathie obliterante des membres inferieurs",
    "aaa": "anevrisme de l'aorte abdominale",
    "dissection": "dissection aortique",
    "coro": "coronarographie",
    "angio": "angiographie",
    "ecg": "electrocardiogramme",
    "ett": "echocardiographie transthoracique",
    "eto": "echocardiographie transoesophagienne",
    "holter": "holter ecg",
    "mapa": "mesure ambulatoire de la pression arterielle",

    # Pneumologie
    "bpco": "bronchopneumopathie chronique obstructive",
    "sahos": "syndrome d'apnees-hypopnees obstructives du sommeil",
    "sras": "syndrome respiratoire aigu severe",
    "sdra": "syndrome de detresse respiratoire aigue",
    "efr": "explorations fonctionnelles respiratoires",
    "vems": "volume expiratoire maximal par seconde",
    "cvf": "capacite vitale forcee",
    "tif": "rapport de tiffeneau vems/cvf",
    "gds": "gaz du sang arteriel",
    "pao2": "pression partielle en oxygene",
    "paco2": "pression partielle en dioxyde de carbone",
    "sao2": "saturation arterielle en oxygene",
    "spo2": "saturation pulsee en oxygene",
    "dlco": "diffusion du monoxyde de carbone",
    "pno": "pneumothorax",
    "pac": "pneumonie aigue communautaire",
    "ppc": "pression positive continue",
    "vni": "ventilation non invasive",
    "fibro": "fibroscopie bronchique",
    "lba": "lavage broncho-alveolaire",
    "tuberculose": "infection a mycobacterium tuberculosis",
    "bk": "bacille de koch",

    # Nephrologie / Urologie / Metabolisme
    "ira": "insuffisance renale aigue",
    "irc": "insuffisance renale chronique",
    "dfg": "debit de filtration glomerulaire",
    "ckd-epi": "formule ckd-epi estimation du dfg",
    "gna": "glomerulonephrite aigue",
    "gnc": "glomerulonephrite chronique",
    "gem": "glomerulonephrite extra-membraneuse",
    "lmc": "lesions glomerulaires minimes",
    "hfs": "hyalinose segmentaire et focale",
    "gnmp": "glomerulonephrite membrano-proliferative",
    "pbr": "ponction biopsie renale",
    "sn": "syndrome nephrotique",
    "nephro": "nephropathie",
    "ecbu": "examen cytobacteriologique des urines",
    "bu": "bandelette urinaire",
    "iue": "incontinence urinaire d'effort",
    "raub": "retention aigue d'urine",
    "pna": "pyelonephrite aigue",
    "gaj": "glycemie a jeun",
    "hba1c": "hemoglobine glyquee",
    "dt1": "diabete de type 1",
    "dt2": "diabete de type 2",
    "did": "diabete insulino-dependant",
    "dnid": "diabete non insulino-dependant",
    "acidocetose": "acidocetose diabetique",
    "eal": "exploration d'une anomalie lipidique",
    "ldl": "cholesterol ldl",
    "hdl": "cholesterol hdl",
    "tg": "triglycerides",
    "tsh": "thyreostimuline",
    "t3": "triiodothyronine",
    "t4": "thyroxine",

    # Hepato-gastro-enterologie
    "rgo": "reflux gastro-oesophagien",
    "mici": "maladie inflammatoire chronique de l'intestin",
    "rch": "rectocolite hemorragique",
    "crohn": "maladie de crohn",
    "chc": "carcinome hepatocellulaire",
    "nash": "steatohepatite non alcoolique",
    "nafld": "steatose hepatique non alcoolique",
    "fogd": "fibroscopie oesogastroduodenale",
    "eogd": "endoscopie oesogastroduodenale",
    "colo": "coloscopie",
    "cpre": "cholangio-pancreatographie retrograde endoscopique",
    "bili-irm": "cholangio-irm",
    "eoh": "alcoolisme intoxication ethylique chronique",
    "tgo": "aspartate aminotransferase asat",
    "tgp": "alanine aminotransferase alat",
    "asat": "aspartate aminotransferase",
    "alat": "alanine aminotransferase",
    "pal": "phosphatases alcalines",
    "ggt": "gamma glutamyl transferase",
    "vih": "virus de l'immunodeficience humaine",
    "vhb": "virus de l'hepatite b",
    "vhc": "virus de l'hepatite c",

    # Neurologie / Psychiatrie / Geriatrie
    "sep": "sclerose en plaques",
    "sla": "sclerose laterale amyotrophique",
    "tc": "traumatisme cranien",
    "sdc": "syndrome du canal carpien",
    "pl": "ponction lombaire",
    "eeg": "electroencephalogramme",
    "emg": "electromyogramme",
    "irm": "imagerie par resonance magnetique",
    "tdm": "tomodensitometrie scanner",
    "tep": "tomographie par emission de positons",
    "mms": "mini mental state examination",
    "edss": "expanded disability status scale",
    "nihss": "national institutes of health stroke scale",
    "glasgow": "score de glasgow coma scale",
    "gds-score": "geriatric depression scale",
    "ts": "tentative de suicide",
    "bdc": "bouffee delirante aigue",
    "bda": "bouffee delirante aigue",
    "tca": "troubles du comportement alimentaire",
    "toc": "troubles obsessionnels compulsifs",
    "tag": "trouble anxieux generalise",
    "ptsd": "trouble de stress post-traumatique",
    "tspt": "trouble de stress post-traumatique",

    # Rhumatologie / Medecine Interne / Immunologie
    "pr": "polyarthrite rhumatoide",
    "spa": "spondyloarthrite ankylosante",
    "ppr": "pseudopolyarthrite rhizomelique",
    "horton": "arterite a cellules geantes de horton",
    "les": "lupus erythemateux systemique",
    "sapl": "syndrome des antiphospholipides",
    "sgs": "syndrome de gougerot-sjogren",
    "sdrc": "syndrome douloureux regional complexe algodystrophie",
    "crp": "proteine c reactive",
    "vs": "vitesse de sedimentation",
    "pct": "procalcitonine",
    "fan": "facteurs antinucleaires",
    "aanc": "anticorps anti-cytoplasme des neutrophiles",
    "anca": "anticorps anti-cytoplasme des neutrophiles",
    "aant": "anticorps anti-thyroperoxydase",
    "tpo": "anticorps anti-tpo",
    "fr": "facteur rhumatoide",
    "anti-ccp": "anticorps anti-peptides citrullines",

    # Hematologie / Oncologie
    "nfs": "numeration formule sanguine hemogramme",
    "tp": "taux de prothrombine",
    "tca-bio": "temps de cephaline activee",
    "inr": "international normalized ratio",
    "myelo": "myelogramme",
    "bom": "biopsie osteomedullaire",
    "llc": "leucemie lymphoide chronique",
    "lmc-bio": "leucemie myeloide chronique",
    "lam": "leucemie aigue myeloide",
    "lal": "leucemie aigue lymphoblastique",
    "smd": "syndrome myelodysplasique",
    "lh": "lymphome de hodgkin",
    "lnh": "lymphome non hodgkinien",
    "mm": "myelome multiple de kahler",
    "mgus": "gammapathie monoclonale de signification indeterminee",
    "mat": "microangiopathie thrombotique",
    "ptti": "purpura thrombotique thrombocytopenique",
    "shu": "syndrome hemolytique et uremique",
    "pti": "purpura thrombopenique immunologique",
    "civd": "coagulation intravasculaire disseminee",

    # Gynecologie / Pediatrie / Infectiologie / General
    "atcd": "antecedents",
    "aeg": "alteration de l'etat general",
    "ivg": "interruption volontaire de grossesse",
    "img": "interruption medicale de grossesse",
    "fcs": "fausse couche spontanee",
    "geu": "grossesse extra-uterine",
    "pma": "procreation medicalement assistee",
    "amp": "assistance medicale a la procreation",
    "sa": "semaines d'amenorrhee",
    "rciu": "retard de croissance intra-uterin",
    "hta-g": "hypertension arterielle gravidique",
    "pre-eclampsie": "preeclampsie",
    "ist": "infections sexuellement transmissibles",
    "mst": "maladies sexuellement transmissibles",
    "orl": "oto-rhino-laryngologie",
    "tiac": "toxi-infection alimentaire collective",
}

FRENCH_CLINICAL_SYNONYMS = {
    "crise cardiaque": "infarctus du myocarde",
    "attaque cerebrale": "accident vasculaire cerebral",
    "mal de tete": "cephalee",
    "maux de tete": "cephalees",
    "saignement de nez": "epistaxis",
    "crachat de sang": "hemoptysie",
    "vomissement de sang": "hematemese",
    "sang dans les selles": "rectorragie / melena",
    "selles noires": "melena",
    "jaunisse": "ictere",
    "calcul biliaire": "lithiase vesiculaire",
    "calcul renal": "lithiase urinaire / colique nephretique",
    "colique nephretique": "lithiase urinaire",
    "gorge qui brule": "pyrosis",
    "brulure d'estomac": "pyrosis / rgo",
    "difficulte a respirer": "dyspnee",
    "essoufflement": "dyspnee",
    "difficulte a avaler": "dysphagie",
    "douleur a la deglutition": "odynophagie",
    "perte de connaissance": "syncope",
    "malaise": "lipothymie / syncope",
    "bleu": "ecchymose / hematome",
    "ganglion": "adenopathie",
    "ganglions": "adenopathies",
    "gros foie": "hepatomegalie",
    "grosse rate": "splenomegalie",
    "gros rein": "nephromegalie",
    "liquide dans le ventre": "ascite",
    "liquide dans le poumon": "epanchement pleural / pleuresie",
    "suivie du diabete": "surveillance du diabete / hba1c",
}

def build_french_aliases(output: Path, release: str = "2026.1") -> dict:
    records = []
    seen = set()

    for brand, generic in FRENCH_DRUGS_MAPPING.items():
        alias_norm = normalize(brand)
        canonical_norm = normalize(generic)
        if not alias_norm or not canonical_norm or alias_norm == canonical_norm:
            continue
        key = (alias_norm, canonical_norm)
        if key not in seen:
            seen.add(key)
            records.append({
                "alias": brand.strip(),
                "alias_norm": alias_norm,
                "canonical": generic.strip(),
                "canonical_norm": canonical_norm,
                "kind": "ansm_bdpm",
            })

    for acronym, expanded in FRENCH_ACRONYMS_MAPPING.items():
        alias_norm = normalize(acronym)
        canonical_norm = normalize(expanded)
        if not alias_norm or not canonical_norm or alias_norm == canonical_norm:
            continue
        key = (alias_norm, canonical_norm)
        if key not in seen:
            seen.add(key)
            records.append({
                "alias": acronym.strip().upper(),
                "alias_norm": alias_norm,
                "canonical": expanded.strip(),
                "canonical_norm": canonical_norm,
                "kind": "edn_r2c_acronym",
            })

    for lay_term, medical_term in FRENCH_CLINICAL_SYNONYMS.items():
        alias_norm = normalize(lay_term)
        canonical_norm = normalize(medical_term)
        if not alias_norm or not canonical_norm or alias_norm == canonical_norm:
            continue
        key = (alias_norm, canonical_norm)
        if key not in seen:
            seen.add(key)
            records.append({
                "alias": lay_term.strip(),
                "alias_norm": alias_norm,
                "canonical": medical_term.strip(),
                "canonical_norm": canonical_norm,
                "kind": "french_clinical_synonym",
            })

    records.sort(key=lambda item: (item["alias_norm"], item["canonical_norm"]))

    payload = {
        "format": 1,
        "source": "BDPM / ANSM / EDN / R2C French Medical Vocabulary",
        "release": release,
        "notice": (
            "French medical terminology and drug aliases derived from BDPM, ANSM, "
            "and French medical curriculum (EDN/R2C). Used for local search expansion."
        ),
        "aliases": records,
    }

    encoded = (json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n").encode("utf-8")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(gzip.compress(encoded, compresslevel=9, mtime=0))

    return {
        "aliases": len(records),
        "uncompressed_bytes": len(encoded),
        "compressed_bytes": output.stat().st_size,
    }

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compile French medical aliases")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("resources/medical_vocab/french_medical_aliases.json.gz"),
    )
    parser.add_argument("--release", default="2026.1")
    args = parser.parse_args()
    result = build_french_aliases(args.output, args.release)
    print(json.dumps(result, indent=2))
